apiVersion: v1
kind: Namespace
metadata:
  name: thethroneofgames
  labels:
    app: thethroneofgames
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: thethroneofgames-monitoring
  labels:
    app: thethroneofgames
    environment: monitoring
