apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: thethroneofgames
type: Opaque
stringData:
  key: "your-jwt-secret-key-minimum-32-characters-long-change-in-production!"
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: thethroneofgames
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMyakNDQWNJQ0NRQ1hreERaRmVqRlJqQXpBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVJneEd3WURWUVFERXhOMGVIQXQKV0hObGNuWmxjaUJIYjIxaGFXNGdWR1Z6ZEVOMGVIQXhFREF1QmdOVkJBTVRKMnh2WW1GelkyeDViV1Z1ZEVCMApFVEEyTVJneEd3WURWUVFERXhOMGVIQXRXSE5sY25abGNpQkhiMjFoYVc0Z1ZHVnpkRU4wZUhBeEVEQXVCZ05WCkJBTVRKMnh2WW1GelkyeDViV1Z1ZEVCMEJnTlZCQ3dURDJOaGJHaG1iM0p1YVdOaGRHVlRkRzlySUI0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUNYUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQXNDQmpnQVVBRXJN...QVFCRC8rRUo0d0tCakR3QVjFHVGM0QVovckNQQjMrclJYQQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-password
  namespace: thethroneofgames
type: Opaque
stringData:
  SA_PASSWORD: "YourSecurePassword123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: thethroneofgames
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
