{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thethroneofgames.fullname" . }}-api-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: api
data:
  {{- range $key, $value := .Values.configMap.api }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
