{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thethroneofgames.fullname" . }}-api-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "thethroneofgames.selectorLabels" . | nindent 4 }}
    app: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.api.service.metricsPort }}
      targetPort: {{ .Values.api.service.metricsPort }}
      protocol: TCP
{{- end }}

{{- if .Values.rabbitmq.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: rabbitmq
spec:
  type: {{ .Values.rabbitmq.service.type }}
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.service.amqpPort }}
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
      protocol: TCP
    - name: clustering
      port: {{ .Values.rabbitmq.service.clusteringPort }}
      targetPort: {{ .Values.rabbitmq.service.clusteringPort }}
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: rabbitmq
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: {{ .Values.rabbitmq.service.amqpPort }}
    - name: management
      port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: {{ .Values.rabbitmq.service.managementPort }}
    - name: clustering
      port: {{ .Values.rabbitmq.service.clusteringPort }}
      targetPort: {{ .Values.rabbitmq.service.clusteringPort }}
{{- end }}

{{- if .Values.mssql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: mssql
spec:
  type: {{ .Values.mssql.service.type }}
  selector:
    app: mssql
  ports:
    - name: sql
      port: {{ .Values.mssql.service.port }}
      targetPort: {{ .Values.mssql.service.port }}
      protocol: TCP
{{- end }}

{{- if .Values.prometheus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: prometheus
  ports:
    - name: web
      port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
      protocol: TCP
{{- end }}

{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: grafana
  ports:
    - name: web
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
      protocol: TCP
{{- end }}
