{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thethroneofgames.fullname" . }}-api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "thethroneofgames.labels" . | nindent 4 }}
    app: api
{{- end }}
